### ISSUE TITLE
Manifest v3

### ISSUE THREAD

**Issue by Garito** [antony/sveltekit-adapter-browser-extension#10]
Hi
Chrome is raising a warning about the version 2 so I'm trying to use v3
Would this library migrate to version 3? When?
If not:
How can I prevent the creation of the browser_action key?

Thanks

**Comment by FireMakeThunder** [comment]
I think the `manifest.json` from build will still work but you'll get the warning `'browser_action' requires manifest version of 2 or lower.`

### Defaults:
ATM, you can override default values for `manifest.json` but not prevent their creation.

**Comment by FireMakeThunder** [comment]
AFAIK, you can override default values for `manifest.json` but not prevent their creation.
