### ISSUE TITLE
Address breaking adapter API changes in #4192

### ISSUE THREAD

**Issue by Theo-Steiner** [antony/sveltekit-adapter-browser-extension#8]
Up until a few days ago @FireMakeThunder's [fix for the previous breaking adapter changes worked great](https://github.com/FireMakeThunder/sveltekit-adapter-browser-extension/tree/sveltekit-adapt-api-patch), but in rapidly changing svelte-kit land nothing stays the same and there again have been breaking changes to the adapter API, that will need to be addressed for this adapter to work properly. 
sveltejs/kit#4192 moved the prerendering from the adapt to the build step and introduced a config option for adapter-static like behaviour at config.kit.prerender.default.

Until a PR for addressing this breaking change is merged, you can still use this adapter by simply installing ``npm install -D Theo-Steiner/sveltekit-adapter-browser-extension`` and modify your config to look like this:
```javascript
import adapterBrowserExtension from 'sveltekit-adapter-browser-extension';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		prerender: {
			default: true
		},
		adapter: adapterBrowserExtension(),
		appDir: 'ext'
	}
};

export default config;
```

**Comment by Theo-Steiner** [comment]
this also addresses #6

**Comment by antony** [comment]
Thank you!
